defaults: &defaults
  roots:
    - hellcat
    - user
  bubble_colors:
    - '#2d2c2d'
    - '#8b99c2'
    - '#97B9C5'
    - '#F18FA6'
    - '#C98BB0'
    - '#91c0ed'

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults